// Estados de la asistencia del trabajador

const ESTADO_PRESENTE = "PRESENTE";
const ESTADO_FALTA_JUSTIFICADA = "FALTA JUSTIFICADA";
const ESTADO_TARDANZA = "TARDANZA";
const ESTADO_SALIDA_ANTICIPADA = "SALIDA ANTICIPADA";
const ESTADO_ASISTIO = "ASISTIO";
const ESTADO_ASISTIO_TARDE = "ASISTIO TARDE";

module.exports = { 
    ESTADO_PRESENTE,
    ESTADO_FALTA_JUSTIFICADA,
    ESTADO_TARDANZA,
    ESTADO_SALIDA_ANTICIPADA,
    ESTADO_ASISTIO,
    ESTADO_ASISTIO_TARDE,
}